### ISSUE TITLE
Directview option for launch from course view

### ISSUE THREAD

**Issue by piersharding** [RusticiSoftware/SCORMCloud_MoodleModule#15]
Hi -

I'm doing an enhancement of mod/scormcloud for a client that enables the SCORM object to be (pseudo) launched directly from the course view.  This isn't so much an issue, as asking the question of whether the project maintainers would be interested in reviewing the modification for possible inclusion.  At the moment this has been done for 1.9 and will be done for 2.x some time next year when the client upgrades.

Cheers,
Piers Harding.

**Comment by danmarsden** [comment]
Hi Piers - closing this for now as it doesn't look like you filed a pull request - we can look at it again if you get round to pushing one through. Thanks!
