### ISSUE TITLE
Possible installation issue

### ISSUE THREAD

**Issue by danielbush** [RusticiSoftware/SCORMCloud_MoodleModule#16]
Hi,
We are using the scorm cloud plugin and getting an error when totara is setting up plugin tables (totara is a modified moodle 1.9 but I have been informed a similar issue occurred in moodle as well):

admin/report/scormcloud plugin needs upgrading
Duplicate entry 'report/courseoverview:view' for key 'mdl_capa_nam_uix'

INSERT INTO mdl_capabilities ( NAME, CAPTYPE, CONTEXTLEVEL, COMPONENT, RISKBITMASK ) VALUES ( 'report/courseoverview:view', 'read', 10, 'report/scormcloud', 8 )

    line 1565 of lib/dmllib.php: call to debugging()
    line 3363 of lib/accesslib.php: call to insert_record()
    line 154 of lib/adminlib.php: call to update_capabilities()
    line 468 of admin/index.php: call to upgrade_plugins()

The version we're using is not  completely clear to me.  I will need to speak again with the person in our sydney office because I think we were given a zip/tarball rather than cloning from git.

**Comment by danmarsden** [comment]
Hey Daniel - drop me an e-mail if you think this is still an issues, but I don't see anyone finding the time to improve 1.9 support - although looking at the error I suspect some of the errors are coming from something other than the SCORM Cloud code.
